// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pocketbase/pocketbase"
	"github.com/sephory/panda-bot/internal/database"
	"github.com/sephory/panda-bot/internal/panda"
)

// Injectors from wire.go:

func InitializePanda() (*panda.Panda, error) {
	config := ReadConfig()
	botConfig := GetBotConfig(config)
	pocketBase := pocketbase.New()
	databaseDatabase := database.New(pocketBase)
	v := GetChatClients(config)
	bot := panda.NewBot(botConfig, databaseDatabase, v...)
	pandaPanda := panda.New(bot, pocketBase, databaseDatabase)
	return pandaPanda, nil
}
